# Generated by Django 5.0.3 on 2025-02-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Laboratoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('Maintenance', 'En maintenance'), ('Hors_service', 'Hors Service')], default='Disponible', max_length=20)),
                ('mutualisable', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materiels/images/')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laboratoire.laboratoire')),
            ],
        ),
    ]
