# Generated by Django 5.0.3 on 2025-02-24 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Laboratoire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='laboratoires', to=settings.AUTH_USER_MODEL),
        ),
    ]
