# Generated by Django 5.0.3 on 2025-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('RESERVATION_CREATED', 'Réservation créée'), ('RESERVATION_UPDATED', 'Réservation mise à jour'), ('RESERVATION_DELETED', 'Réservation supprimée'), ('RESERVATION_ACCEPTED', 'Réservation acceptée'), ('RESERVATION_REJECTED', 'Réservation refusée'), ('EQUIPMENT_ADDED', 'Équipement ajouté'), ('EQUIPMENT_UPDATED', 'Équipement mis à jour'), ('EQUIPMENT_DELETED', 'Équipement supprimé')], max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique des actions',
                'verbose_name_plural': 'Historique des actions',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STATISTIQUES', 'Statistiques'), ('ACTIVITES', 'Activités'), ('PREVISIONS', 'Prévisions')], max_length=50)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/pdf/')),
                ('fichier_excel', models.FileField(blank=True, null=True, upload_to='rapports/excel/')),
            ],
        ),
    ]
